### ISSUE TITLE
dora-coordinator has very high CPU usage

### ISSUE THREAD

**Issue by heyong4725** [dora-rs/dora#154]
Env: Ubuntu 22.04
Dora Release: 0.1.1 (0.1.0 on MacOS has similar issue)

Python example:
1. After dora up, CPU usage seems normal
2. dora start python example, CPU usage become very high
3. after dora stop, CPU usage still very high (4 of 16 CPU cores reach 100%), htop command shows dora-coordinator on 4 CPU cores, reach 100%
4. after dora destroy, CPU usage back to normal

Rust example (I can build dora new rust_proj example using 0.1.1:): 
1. After dora up, CPU usage seems normal
2. dora start rust example, CPU usage become very high
3. after dora stop, CPU usage is still very high (2 of 16 CPU cores reach 100%), htop command shows dora-coordinator on 2 CPU cores, reach 100%
4. after dora destroy, CPU usage back to normal

Ths issue is why after dora stop the dataflow, the dora-coordinator has such a high CPU usage. Further more, dora-coordinator as a control plane component, it should not have high CPU usage 

@phil-opp please take a look

**Comment by phil-opp** [comment]
Thanks for reporting! The issue was that we kept polling closed control connections for new messages. Trying to read from a closed socket results in an `UnexpectedEof` error immediately, so we kept the CPU quite busy when we tried to receive in a `loop`. I opened #155 to fix this by breaking out of the loop on `UnexpectedEof` errors.
